### ISSUE TITLE
Unpack exception

### ISSUE THREAD

**Issue by Psyxoz13** [Dexesttp/hkxpack#26] opened 2023-01-06 10:59 UTC
When i try to unpack hkx i get this error:
Exception in thread "main" java.lang.IllegalArgumentException: newPosition > limit: (24948 > 3284)
        at java.nio.Buffer.createPositionException(Unknown Source)
        at java.nio.Buffer.position(Unknown Source)
        at com.dexesttp.hkxpack.hkx.classnames.ClassnamesInterface.extract(ClassnamesInterface.java:69)
        at com.dexesttp.hkxpack.hkxreader.HKXReaderConnector.<init>(HKXReaderConnector.java:46)
        at com.dexesttp.hkxpack.hkxreader.HKXReader.read(HKXReader.java:78)
        at com.dexesttp.hkxpack.cli.commands.Command_unpack.executionCore(Command_unpack.java:30)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.executeSingle(Command_IO.java:134)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.execute(Command_IO.java:116)
        at com.dexesttp.hkxpack.cli.ConsoleView.main(ConsoleView.java:31)

**Comment by Dexesttp** [comment] 2024-10-13 10:03
Hello,

Sorry, I'm just getting to unpiling issues here. This error looks like you're trying to unpack hkx files that do not come from FO4, otherwise please point to the specific main game file you're trying to tinker with because there'd be something very weird happening with this file.

Given that it's been a year and a half, I'm guessing the issue is either solved or no longer relevant, so I'll just close the issue for now. Feel free to comment if you actually have more to add.

**Closed as not planned by Dexesttp** 2024-10-13 10:03 UTC
